imports:
    - { resource: integrations/quickbooks.yml }

services:

    api.event.authentication_success_listener:
        class: App\EventListener\Security\JwtAuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    api.jwt_token_handler:
        class: App\Security\Jwt\JwtHandler
        arguments: ['@lexik_jwt_authentication.encoder']

    api.jwt_token_authenticator:
        class: App\Security\Authentication\Authenticator\JwtAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder', '@api.jwt_token_handler', '%timezone%']

    api.cors_listener:
        class: App\EventListener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    api.auth.login_attempts:
        class: App\Services\LoginAttemptHandler
        calls:
            - [setContainer, ['@service_container']]
        arguments: ['@doctrine.orm.entity_manager', '%login_attempt_minutes%', '%max_login_attempts%']