# vim:ft=ansible:
---

- name: check for old letsencrypt client
  stat: path=/opt/letsencrypt/acme
  register: st

- name: remove old letsencrypt client
  file: path=/opt/letsencrypt state=absent
  when: st.stat.isdir is defined and st.stat.isdir

- name: download certbot
  get_url: url=https://dl.eff.org/certbot-auto dest=/usr/local/bin mode=755

  # all certbot-auto commands must be prefixed with `XDG_DATA_HOME=/opt`
- name: install dependencies
  shell: XDG_DATA_HOME=/opt /usr/local/bin/certbot-auto plugins --noninteractive

- name: build letsencrypt command
  set_fact:
    letsencrypt_command: XDG_DATA_HOME=/opt /usr/local/bin/certbot-auto run -m dev@zoadilack.com -d {{ host_name }} {{ redirect_domains | length | ternary('-d ','') }}{{ redirect_domains | join(' -d ') }} --agree-tos --expand --no-redirect --apache --text --keep-until-expiring --no-self-upgrade

- name: install SSL certificate
  command: "{{ letsencrypt_command }}"
  when: use_letsencrypt

- name: create ssl certificate renewal cron
  cron: name="ssl certificate renewal for {{ host_name }}" minute="30" hour="2" weekday="0" state="present" job="{{ letsencrypt_command }}" user={{ login_user }}
  when: use_letsencrypt