version: 0.0
os: linux
files:
  - source: api/api
    destination: /var/www/tavro
permissions:
  - object: /var/www/tavro/api
    owner: www-data
    group: www-data
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: deploy/build.sh
      runas: root