# You can use a Docker image from Docker Hub or your own container registry
image: epcallan/phpunit-php7
   
pipelines:
  default:
    - step:
        script:
          - sudo apt-get install -y php7.0-fpm php7.0-cli php7.0-curl php7.0-common php7.0-json php7.0-opcache php7.0-mysql php7.0-phpdbg php7.0-gd php7.0-imap php7.0-ldap php7.0-pgsql php7.0-pspell php7.0-recode php7.0-snmp php7.0-tidy php7.0-dev php7.0-intl php7.0-mbstring php7.0-bcmath
          - composer --version
          - phpunit --version
          - mkdir ~/.ssh
          - echo $TAVRO_CORE_DEPLOYMENT_KEY > ~/.ssh/id_rsa.tmp # note: assumes base64 encoded ssh key without a passphrase
          - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - base64 ~/.ssh/id_rsa
          - 'echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null" > ~/.ssh/config'
          - cd api && composer install --prefer-dist -n
          - cd api && phpunit --configuration api/phpunit.xml