# You can use a Docker image from Docker Hub or your own container registry
image: phpunit/phpunit:5.0.3
   
pipelines:
  default:
    - step:
        script:
          - composer --version
          - phpunit --version
          - cd api && composer install
          - cd api && phpunit --configuration api/phpunit.xml