# You can use a Docker image from Docker Hub or your own container registry
image: epcallan/phpunit-php7
   
pipelines:
  default:
    - step:
        script:
          - bash deploy/build.sh
          - zip -r /tmp/artifact.zip api/*
          - python deploy/aws_codedeploy.yml