version: '2'

services:

  api_db:
    image: mysql
    container_name: "api_db"
    restart: always
    ports:
      - ${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  # api_db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
      - ./docker/init.sh:/var/www/html/bin/init.sh
    ports:
      - 80
    links:
      - api_db