tavro_api_commands:
    resource: "@TavroApiBundle/Resources/config/routing/commands.yml"

tavro_auth_api:
    resource: "@TavroApiBundle/Resources/config/routing/auth.yml"

tavro_comment_api:
    resource: "@TavroApiBundle/Resources/config/routing/comment.yml"

tavro_contact_api:
    resource: "@TavroApiBundle/Resources/config/routing/contact.yml"

tavro_person_api:
    resource: "@TavroApiBundle/Resources/config/routing/person.yml"

tavro_shareholder_api:
    resource: "@TavroApiBundle/Resources/config/routing/shareholder.yml"

tavro_tag_api:
    resource: "@TavroApiBundle/Resources/config/routing/tag.yml"

tavro_user_api:
    resource: "@TavroApiBundle/Resources/config/routing/user.yml"

tavro_user_security_api:
    resource: "@TavroApiBundle/Resources/config/routing/user_security.yml"

tavro_user_quickbooks_api:
    resource: "@TavroApiBundle/Resources/config/routing/user_quickbooks.yml"

tavro_user_freshbooks_api:
    resource: "@TavroApiBundle/Resources/config/routing/user_freshbooks.yml"

tavro_log_api:
    resource: "@TavroApiBundle/Resources/config/routing/log.yml"

# --------------------------------
#  Routes that require an Account
# --------------------------------

tavro_account_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/account.yml"
    prefix: "/accounts/{account}"

tavro_account_group_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/account_group.yml"
    prefix: "/accounts/{account}"

tavro_account_user_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/account_user.yml"
    prefix: "/accounts/{account}"

tavro_expense_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/expense.yml"
    prefix: "/accounts/{account}"

tavro_expense_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/expense_category.yml"
    prefix: "/accounts/{account}"

tavro_forecast_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/forecast.yml"
    prefix: "/accounts/{account}"

tavro_forecast_revenue_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/forecast_revenue.yml"
    prefix: "/accounts/{account}"

tavro_forecast_expense_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/forecast_expense.yml"
    prefix: "/accounts/{account}"

tavro_forecast_staff_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/forecast_staff.yml"
    prefix: "/accounts/{account}"

tavro_funding_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/funding.yml"
    prefix: "/accounts/{account}"

tavro_node_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/node.yml"
    prefix: "/accounts/{account}"

tavro_organization_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/organization.yml"
    prefix: "/accounts/{account}"

tavro_product_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/product.yml"
    prefix: "/accounts/{account}"

tavro_product_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/product_category.yml"
    prefix: "/accounts/{account}"

tavro_revenue_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/revenue.yml"
    prefix: "/accounts/{account}"

tavro_revenue_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/revenue_category.yml"
    prefix: "/accounts/{account}"

tavro_service_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/service.yml"
    prefix: "/accounts/{account}"

tavro_service_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account/service_category.yml"
    prefix: "/accounts/{account}"
