tavro_api_commands:
    resource: "@TavroApiBundle/Resources/config/routing/commands.yml"

tavro_jwt_api:
    resource: "@TavroApiBundle/Resources/config/routing/jwt.yml"

tavro_log_api:
    resource: "@TavroApiBundle/Resources/config/routing/log.yml"

tavro_slack_api:
    resource: "@TavroApiBundle/Resources/config/routing/slack.yml"

tavro_user_security_api:
    resource: "@TavroApiBundle/Resources/config/routing/security.yml"

# --------------------------------------
#  Routes that require an Entity
# --------------------------------------
tavro_account_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/account.yml"

tavro_account_type_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/account_type.yml"

tavro_comment_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/comment.yml"

tavro_contact_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/contact.yml"

tavro_person_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/person.yml"

tavro_shareholder_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/shareholder.yml"

tavro_tag_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/tag.yml"

tavro_user_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/user.yml"

tavro_user_quickbooks_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/user_quickbooks.yml"

tavro_user_freshbooks_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/user_freshbooks.yml"

tavro_forecast_revenue_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/forecast_revenue.yml"

tavro_forecast_expense_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/forecast_expense.yml"

tavro_forecast_staff_api:
    resource: "@TavroApiBundle/Resources/config/routing/entity/forecast_staff.yml"

# --------------------------------------
#  Routes that require an AccountEntity
# --------------------------------------
tavro_account_group_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/account_group.yml"
    prefix: "/accounts/{account}"

tavro_account_user_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/account_user.yml"
    prefix: "/accounts/{account}"

tavro_expense_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/expense.yml"
    prefix: "/accounts/{account}"

tavro_expense_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/expense_category.yml"
    prefix: "/accounts/{account}"

tavro_forecast_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/forecast.yml"
    prefix: "/accounts/{account}"

tavro_funding_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/funding.yml"
    prefix: "/accounts/{account}"

tavro_node_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/node.yml"
    prefix: "/accounts/{account}"

tavro_organization_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/organization.yml"
    prefix: "/accounts/{account}"

tavro_product_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/product.yml"
    prefix: "/accounts/{account}"

tavro_product_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/product_category.yml"
    prefix: "/accounts/{account}"

tavro_revenue_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/revenue.yml"
    prefix: "/accounts/{account}"

tavro_revenue_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/revenue_category.yml"
    prefix: "/accounts/{account}"

tavro_service_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/service.yml"
    prefix: "/accounts/{account}"

tavro_service_category_api:
    resource: "@TavroApiBundle/Resources/config/routing/account-entity/service_category.yml"
    prefix: "/accounts/{account}"
