services:

# ================
# SECURITY & AUTH
# ================

    tavro.angular_api_authenticator:
        class:     Tavro\Bundle\ApiBundle\Security\AngularApiAuthenticator
        arguments: ["@tavro.user_provider"]

    tavro.api_authenticator:
        class:     Tavro\Bundle\ApiBundle\Security\ApiAuthenticator
        arguments: ["@tavro.user_provider"]

# =========
# HANDLERS
# =========
    tavro.handler.roles:
        class: Tavro\Bundle\ApiBundle\Handler\RoleHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Role]

    tavro.handler.users:
        class: Tavro\Bundle\ApiBundle\Handler\UserHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\User]

    tavro.handler.comments:
        class: Tavro\Bundle\ApiBundle\Handler\CommentHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Comment]

    tavro.handler.files:
        class: Tavro\Bundle\ApiBundle\Handler\FileHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\File]

    tavro.handler.images:
        class: Tavro\Bundle\ApiBundle\Handler\ImageHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Image]

    tavro.handler.nodes:
        class: Tavro\Bundle\ApiBundle\Handler\NodeHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Node]

    tavro.handler.variables:
        class: Tavro\Bundle\ApiBundle\Handler\RoleHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Variable]

    tavro.handler.tags:
        class: Tavro\Bundle\ApiBundle\Handler\TagHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Tag]

    tavro.handler.node_tags:
        class: Tavro\Bundle\ApiBundle\Handler\NodeTagHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\NodeTag]

    tavro.handler.organizations:
        class: Tavro\Bundle\ApiBundle\Handler\OrganizationHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\Organization]

    tavro.handler.user_organizations:
        class: Tavro\Bundle\ApiBundle\Handler\OrganizationHandler
        arguments: ["@service_container", "@doctrine.orm.main_entity_manager", Tavro\Bundle\CoreBundle\Entity\UserOrganization]