imports:
    - { resource: integrations/quickbooks.yml }

services:

    tavro.event.authentication_success_listener:
        class: Tavro\Bundle\ApiBundle\EventListener\Security\JwtAuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    tavro_api.jwt_token_handler:
        class: Tavro\Bundle\ApiBundle\Security\Jwt\JwtHandler
        arguments: ['@lexik_jwt_authentication.encoder']

    tavro.jwt_token_authenticator:
        class: Tavro\Bundle\ApiBundle\Security\Authentication\Authenticator\JwtAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder', '%timezone%']

    tavro_api.cors_listener:
        class: Tavro\Bundle\ApiBundle\EventListener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    tavro.auth.login_attempts:
        class: Tavro\Bundle\ApiBundle\Services\LoginAttemptHandler
        calls:
            - [setContainer, ['@service_container']]
        arguments: ['@doctrine.orm.entity_manager', '%login_attempt_minutes%', '%max_login_attempts%']