services:

    tavro.event.authentication_success_listener:
        class: Tavro\Bundle\ApiBundle\EventListener\Security\JwtAuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    tavro.jwt_token_authenticator:
        class: Tavro\Bundle\ApiBundle\Security\Authentication\Authenticator\JwtAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder']

    tavro_api.subscriber.exception:
        class: Tavro\Bundle\ApiBundle\EventSubscriber\Exception\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["%kernel.debug%", "@serializer"]