services:

    tavro.event.authentication_success_listener:
        class: Tavro\Bundle\ApiBundle\EventListener\Security\JwtAuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
