api_get_contact:
    path: /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:get, _format: json, entity: "contacts" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_contacts:
    path:  /contacts.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:getAll, _format: json, entity: "contacts" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_contact:
    path:  /contacts.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:post, _format: json, entity: "contacts" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_contact:
    path:  /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:patch, _format: json, entity: "contacts" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_contact:
    path:  /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:put, _format: json, entity: "contacts" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_contact:
    path:  /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:delete, _format: json, entity: "contacts" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_contacts:
    path:  /typeahead/contacts.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:typeahead, _format: json }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_contact_comments:
    path: /contacts/{contact}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:comments, _format: json}
    methods: [GET|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml

api_new_contact_comment:
    path: /contacts/{contact}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Contact:newComment, _format: json}
    methods: [POST|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml
