api_forecast_revenues:
    path: /forecasts/{forecast}/revenues.{_format}
    defaults: { _controller: TavroApiBundle:Entity\ForecastRevenue:byForecast, _format: json}
    methods: [GET|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml