remove_trailing_slash:
    path: /{url}
    defaults: { _controller: TavroAppBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: get

security:
    resource: "@TavroAppBundle/Resources/config/routing/security.yml"

tavro:
    resource: "@TavroAppBundle/Resources/config/routing/default.yml"

