remove_trailing_slash:
    path: /{url}
    defaults: { _controller: TavroAppBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: get

tavro_admin:
    resource: "@TavroAppBundle/Resources/config/routing/admin.yml"
default:
    resource: "@TavroAppBundle/Resources/config/routing/default.yml"
security:
    resource: "@TavroAppBundle/Resources/config/routing/security.yml"