remove_trailing_slash:
    path: /{url}
    defaults: { _controller: TavroAppBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: get

index:
    path: /
    defaults: { _controller: "TavroAppBundle:Default:index" }

security:
    resource: "@TavroAppBundle/Resources/config/routing/security.yml"

documentation:
    resource: "@TavroAppBundle/Resources/config/routing/documentation.yml"
    prefix: /docs