api_get_account_type:
    path: /account_types/{id}.{_format}
    defaults: { _controller: Entity\AccountType:get, _format: json, entity: "account_types" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_account_types:
    path:  /account_types.{_format}
    defaults: { _controller: Entity\AccountType:getAll, _format: json, entity: "account_types" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_account_type:
    path:  /account_types.{_format}
    defaults: { _controller: Entity\AccountType:post, _format: json, entity: "account_types" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_account_type:
    path:  /account_types/{id}.{_format}
    defaults: { _controller: Entity\AccountType:patch, _format: json, entity: "account_types" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_account_type:
    path:  /account_types/{id}.{_format}
    defaults: { _controller: Entity\Account:put, _format: json, entity: "account_types" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_account_type:
    path:  /account_types/{id}.{_format}
    defaults: { _controller: Entity\Account:delete, _format: json, entity: "account_types" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml