api_get_entity:
    path: /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_entities:
    path:  /{entity}.{_format}
    defaults: { _controller: TavroApiBundle:Api:getAll, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_post_entity:
    path:  /{entity}.{_format}
    defaults: { _controller: TavroApiBundle:Api:post, _format: json }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_entity:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_entity:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_entity:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_entities:
    path:  /typeahead/{entity}.{_format}
    defaults: { _controller: TavroApiBundle:Api:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml