api_import_hubspot:
    path: /accounts/{account}/import/hubspot.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Hubspot:hubspotImport, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_import_qbo:
    path: /accounts/{account}/import/qbo.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Command:qboImport, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml