api_get_comment:
    path: /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Comment:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_patch_comment:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Comment:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_comment:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Comment:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_comment:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Comment:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_comments:
    path:  /typeahead/{entity}.{_format}
    defaults: { _controller: TavroApiBundle:Comment:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml