api_get_customer:
    path: /customers/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Customer:get, _format: json, entity: "customers" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_customers:
    path:  /customers.{_format}
    defaults: { _controller: TavroApiBundle:Customer:getAll, _format: json, entity: "customers" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_customer:
    path:  /customers.{_format}
    defaults: { _controller: TavroApiBundle:Customer:post, _format: json, entity: "customers" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_customer:
    path:  /customers/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Customer:patch, _format: json, entity: "customers" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_customer:
    path:  /customers/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Customer:put, _format: json, entity: "customers" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_customer:
    path:  /customers/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Customer:delete, _format: json, entity: "customers" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_customers:
    path:  /typeahead/customers.{_format}
    defaults: { _controller: TavroApiBundle:Customer:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_customer_comments:
    path: /customers/{customer}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Customer:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_customer_comment:
    path: /customers/{customer}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Customer:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml
