api_get_contact:
    path: /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:get, _format: json, entity: "contacts" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_contacts:
    path:  /contacts.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:getAll, _format: json, entity: "contacts" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_contact:
    path:  /contacts.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:post, _format: json, entity: "contacts" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_contact:
    path:  /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:patch, _format: json, entity: "contacts" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_contact:
    path:  /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:put, _format: json, entity: "contacts" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_contact:
    path:  /contacts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:delete, _format: json, entity: "contacts" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_contacts:
    path:  /typeahead/contacts.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_contact_comments:
    path: /contacts/{contact}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_contact_comment:
    path: /contacts/{contact}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Api\Contact:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml
