api_expense_tags:
    path: /{expense}/tags.{_format}
    defaults: { _controller: TavroApiBundle:Expense:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_expense_tag:
    path: /{expense}/tags.{_format}
    defaults: { _controller: TavroApiBundle:Expense:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_expense_comments:
    path: /{expense}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Expense:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_expense_comment:
    path: /{expense}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Expense:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml
