api_forecast_revenues:
    path: /forecasts/{forecast}/revenues.{_format}
    defaults: { _controller: TavroApiBundle:Api\ForecastRevenue:byForecast, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml