api_hubspot_import:
    path: /accounts/{account}/hubspot/import.{_format}
    defaults: { _controller: TavroApiBundle:Hubspot:import, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml