api_jwt_authenticate:
    path: /auth
    methods: [POST|OPTIONS]
    defaults: { _controller: TavroApiBundle:Jwt:tokenAuthenticate }

api_jwt_logout:
    path: /auth/logout
    defaults: { _controller: TavroApiBundle:Jwt:tokenLogout }
    methods: [POST|OPTIONS]