api_node_tags:
    path: /{node}/tags.{_format}
    defaults: { _controller: TavroApiBundle:Node:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_node_tag:
    path: /{node}/tags.{_format}
    defaults: { _controller: TavroApiBundle:Node:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_node_comments:
    path: /{node}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Node:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_node_comment:
    path: /{node}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Node:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml
