api_get_node:
    path: /nodes/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:get, _format: json, entity: "nodes" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_nodes:
    path:  /nodes.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:getAll, _format: json, entity: "nodes" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_node:
    path:  /nodes.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:post, _format: json, entity: "nodes" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_node:
    path:  /nodes/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:patch, _format: json, entity: "nodes" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_node:
    path:  /nodes/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:put, _format: json, entity: "nodes" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_node:
    path:  /nodes/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:delete, _format: json, entity: "nodes" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_delete_node_tag:
    path:  /nodes/{node}/tags/{tag}.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:deleteTag, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_nodes:
    path:  /typeahead/nodes.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml
        
api_node_tags:
    path: /nodes/{node}/tags.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_node_tag:
    path: /nodes/{node}/tags.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_node_comments:
    path: /nodes/{node}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_node_comment:
    path: /nodes/{node}/comments.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_user_nodes:
    path: /users/{user}/nodes.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:byUser, _format: json}
    methods: GET
    requirements:
        user: \d+
        _format: json|xml

api_nodes_by_account:
    path: /accounts/{account}/nodes.{_format}
    defaults: { _controller: TavroApiBundle:Api\Node:byAccount, _format: json}
    methods: GET
    requirements:
        account: \d+
        _format: json|xml