api_get_person:
    path: /people/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:get, _format: json, entity: 'people' }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_person_images:
    path:  /people/{id}/images.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:getImages, _format: json, entity: 'people' }
    methods: GET
    requirements:
        _format:  json|xml

api_post_person_image:
    path:  /people/{person}/images.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:newImage, _format: json, entity: 'people' }
    methods: POST
    requirements:
        _format:  json|xml

api_get_all_people:
    path:  /people.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:getAll, _format: json, entity: 'people' }
    methods: GET
    requirements:
        _format:  json|xml

api_post_person:
    path:  /people.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:post, _format: json, entity: 'people' }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_person:
    path:  /people/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:patch, _format: json, entity: 'people' }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_person:
    path:  /people/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:put, _format: json, entity: 'people' }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_person:
    path:  /people/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:delete, _format: json, entity: 'people' }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_people:
    path:  /typeahead/people.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Person:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml