api_get_service:
    path: /services/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:get, _format: json, entity: 'services' }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_services:
    path:  /services.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:getAll, _format: json, entity: 'services' }
    methods: GET
    requirements:
        _format:  json|xml

api_post_service:
    path:  /services.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:post, _format: json, entity: 'services' }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_service:
    path:  /services/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:patch, _format: json, entity: 'services' }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_service:
    path:  /services/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:put, _format: json, entity: 'services' }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_service:
    path:  /services/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:delete, _format: json, entity: 'services' }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_services:
    path:  /typeahead/services.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_account_services:
    path: /accounts/{account}/services.{_format}
    defaults: { _controller: TavroApiBundle:Entity\Service:byAccount, _format: json}
    methods: GET
    requirements:
        account: \d+
        _format: json|xml