api_get_shareholder:
    path: /shareholders/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:get, _format: json, entity: 'shareholders'  }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_shareholders:
    path:  /shareholders.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:getAll, _format: json, entity: 'shareholders'  }
    methods: GET
    requirements:
        _format:  json|xml

api_post_shareholder:
    path:  /shareholders.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:post, _format: json, entity: 'shareholders'  }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_shareholder:
    path:  /shareholders/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:patch, _format: json, entity: 'shareholders'  }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_shareholder:
    path:  /shareholders/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:put, _format: json, entity: 'shareholders'  }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_shareholder:
    path:  /shareholders/{id}.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:delete, _format: json, entity: 'shareholders'  }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_shareholders:
    path:  /typeahead/shareholders.{_format}
    defaults: { _controller: TavroApiBundle:Shareholder:typeahead, _format: json, entity: 'shareholders'  }
    methods: GET
    requirements:
        _format:  json|xml