api_get_user_quickbooks:
    path: /users/{id}/quickbooks.{_format}
    defaults: { _controller: TavroApiBundle:Entity\UserQuickbooks:get, _format: json, entity: "user_quickbooks" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_post_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: TavroApiBundle:Entity\UserQuickbooks:post, _format: json, entity: "user_quickbooks" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: TavroApiBundle:Entity\UserQuickbooks:patch, _format: json, entity: "user_quickbooks" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: TavroApiBundle:Entity\UserQuickbooks:put, _format: json, entity: "user_quickbooks" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: TavroApiBundle:Entity\UserQuickbooks:delete, _format: json, entity: "user_quickbooks" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml