# ==============
# UNIQUE ROUTES
# ==============
api_user_regenerate_api_key:
    path: /users/{user}/reset/api-key.{_format}
    defaults: { _controller: CamelotApiBundle:User:resetApiKey, _format: json}
    methods: POST
    requirements:
        id: \d+
        _format: json|xml

api_user_regenerate_api_password:
    path: /users/{user}/reset/api-password.{_format}
    defaults: { _controller: CamelotApiBundle:User:resetApiPassword, _format: json}
    methods: POST
    requirements:
        id: \d+
        _format: json|xml