api_get_current_user:
    path: /user.{_format}
    defaults: { _controller: TavroApiBundle:User:getCurrent, _format: json, entity: "users" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_user:
    path: /users/{id}.{_format}
    defaults: { _controller: TavroApiBundle:User:get, _format: json, entity: "users" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_users:
    path:  /users.{_format}
    defaults: { _controller: TavroApiBundle:User:getAll, _format: json, entity: "users" }
    methods: GET
    requirements:
        _format:  json|xml

api_user_signup:
    path:  /signup.{_format}
    defaults: { _controller: TavroApiBundle:User:post, _format: json, entity: "users" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_user:
    path:  /users/{id}.{_format}
    defaults: { _controller: TavroApiBundle:User:patch, _format: json, entity: "users" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_user:
    path:  /users/{id}.{_format}
    defaults: { _controller: TavroApiBundle:User:put, _format: json, entity: "users" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_user:
    path:  /users/{id}.{_format}
    defaults: { _controller: TavroApiBundle:User:delete, _format: json, entity: "users" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_user_regenerate_api_key:
    path: /users/{user}/reset/api-key.{_format}
    defaults: { _controller: TavroApiBundle:User:resetApiKey, _format: json}
    methods: POST
    requirements:
        user: \d+
        _format: json|xml

api_user_regenerate_api_password:
    path: /users/{user}/reset/api-password.{_format}
    defaults: { _controller: TavroApiBundle:User:resetApiPassword, _format: json}
    methods: POST
    requirements:
        user: \d+
        _format: json|xml

api_user_nodes:
    path: /users/{user}/nodes.{_format}
    defaults: { _controller: TavroApiBundle:User:nodes, _format: json}
    methods: GET
    requirements:
        user: \d+
        _format: json|xml

api_user_organizations:
    path: /users/{user}/organizations.{_format}
    defaults: { _controller: TavroApiBundle:User:organizations, _format: json}
    methods: GET
    requirements:
        user: \d+
        _format: json|xml