api_get_entity:
    path: /{entity}/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Default:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_patch_entity:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Default:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_entity:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Default:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_entity:
    path:  /{entity}/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Default:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_entities:
    path:  /typeahead/{entity}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Default:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml