api_get_expense:
    path: /expenses/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_expenses:
    path:  /expenses.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:getAll, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_post_expense:
    path:  /expenses.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:post, _format: json }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_expense:
    path:  /expenses/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_expense:
    path:  /expenses/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_expense:
    path:  /expenses/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_expenses:
    path:  /typeahead/expenses.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml
        
api_expense_tags:
    path: /expenses/{expense}/tags.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_expense_tag:
    path: /expenses/{expense}/tags.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_expense_comments:
    path: /expenses/{expense}/comments.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_expense_comment:
    path: /expenses/{expense}/comments.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Expense:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml
