api_get_node:
    path: /nodes/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_nodes:
    path:  /nodes.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:getAll, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_post_node:
    path:  /nodes.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:post, _format: json }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_node:
    path:  /nodes/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_node:
    path:  /nodes/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_node:
    path:  /nodes/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_nodes:
    path:  /typeahead/nodes.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml
        
api_node_tags:
    path: /nodes/{node}/tags.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_node_tag:
    path: /nodes/{node}/tags.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_node_comments:
    path: /nodes/{node}/comments.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_node_comment:
    path: /nodes/{node}/comments.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Node:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml
