api_get_organization:
    path: /organizations/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:get, _format: json, entity: "organizations" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_organizations:
    path:  /organizations.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:getAll, _format: json, entity: "organizations" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_organization:
    path:  /organizations.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:post, _format: json, entity: "organizations" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:patch, _format: json, entity: "organizations" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:put, _format: json, entity: "organizations" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:delete, _format: json, entity: "organizations" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_organizations:
    path:  /typeahead/organizations.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml
        
api_organization_tags:
    path: /organizations/{organization}/tags.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_organization_tag:
    path: /organizations/{organization}/tags.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_organization_comments:
    path: /organizations/{organization}/comments.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_organization_comment:
    path: /organizations/{organization}/comments.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml


api_organization_users:
    path: /organizations/{organization}/users.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:users, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_services:
    path: /organizations/{organization}/services.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:services, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_service_categories:
    path: /organizations/{organization}/services/categories.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:serviceCategories, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_expenses:
    path: /organizations/{organization}/expenses.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:expenses, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_expense_categories:
    path: /organizations/{organization}/expenses/categories.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:expenseCategories, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_products:
    path: /organizations/{organization}/products.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:products, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_product_categories:
    path: /organizations/{organization}/products/categories.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:productCategories, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_revenues:
    path: /organizations/{organization}/revenues.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:revenues, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_nodes:
    path: /organizations/{organization}/nodes.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:nodes, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_funding:
    path: /organizations/{organization}/funding.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:funding, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_organization_shareholders:
    path: /organizations/{organization}/shareholders.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Organization:shareholders, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml