api_get_product:
    path: /products/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_products:
    path:  /products.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:getAll, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_post_product:
    path:  /products.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:post, _format: json }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_product:
    path:  /products/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_product:
    path:  /products/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_product:
    path:  /products/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_products:
    path:  /typeahead/products.{_format}
    defaults: { _controller: TavroCoreBundle:Api/Product:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml