api_get_revenue_category:
    path: /revenue_categories/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/RevenueCategory:get, _format: json }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_revenue_categories:
    path:  /revenue_categories.{_format}
    defaults: { _controller: TavroCoreBundle:Api/RevenueCategory:getAll, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_post_revenue_category:
    path:  /revenue_categories.{_format}
    defaults: { _controller: TavroCoreBundle:Api/RevenueCategory:post, _format: json }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_revenue_category:
    path:  /revenue_categories/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/RevenueCategory:patch, _format: json }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_revenue_category:
    path:  /revenue_categories/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/RevenueCategory:put, _format: json }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_revenue_category:
    path:  /revenue_categories/{id}.{_format}
    defaults: { _controller: TavroCoreBundle:Api/RevenueCategory:delete, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml