api_jwt_authenticate:
    path: /auth
    methods: [POST|OPTIONS]
    defaults: { _controller: Jwt:tokenAuthenticate }

api_jwt_logout:
    path: /auth/logout
    defaults: { _controller: Jwt:tokenLogout }
    methods: [POST|OPTIONS]