api_jwt_authenticate:
    path: /auth
    methods: [POST|OPTIONS]
    defaults: { _controller: App\Controller\JwtController:tokenAuthenticateAction }

api_jwt_logout:
    path: /auth/logout
    defaults: { _controller: App\Controller\JwtController:tokenLogoutAction }
    methods: [POST|OPTIONS]