api_user_reset_password:
    path: /auth/reset.{_format}
    defaults: { _controller: TavroApiBundle:Security:reset, _format: json }
    methods: [POST|OPTIONS]

api_user_send_reset_password:
    path: /auth/forgot.{_format}
    defaults: { _controller: TavroApiBundle:Security:sendResetToken, _format: json }
    methods: [POST|OPTIONS]

api_user_confirm_email:
    path: /auth/confirm.{_format}
    defaults: { _controller: TavroApiBundle:Security:confirm, _format: json }
    methods: [POST|OPTIONS]

api_user_activate:
    path: /auth/activate.{_format}
    defaults: { _controller: TavroApiBundle:Security:activate, _format: json }
    methods: [POST|OPTIONS]