<?php

namespace Tavro\Repository\Entity;

use Tavro\Repository\TavroRepository;

/**
 * ForecastCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastCommentRepository extends TavroRepository
{
}
