<?php

namespace Tavro\Repository\Entity;

use Tavro\Repository\TavroRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends TavroRepository
{
}
