services:
    tavro.handler.accounts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Account'
    tavro.handler.account_types:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountTypeHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountType'

    tavro.handler.account_users:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\AccountUserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountUser'

    tavro.handler.account_groups:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\AccountGroupHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountGroup'

    tavro.handler.account_group_users:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountGroupUserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountGroupUser'

    tavro.handler.comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\CommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Comment'

    tavro.handler.dashboard:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\DashboardHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Dashboard'

    tavro.handler.dashboard_metric:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\DashboardMetricHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\DashboardMetric'

    tavro.handler.revenue_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RevenueCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\RevenueComment'

    tavro.handler.revenue_categories:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\RevenueCategoryHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\RevenueCategory'

    tavro.handler.forecasts:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\ForecastHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Forecast'

    tavro.handler.forecast_expenses:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ForecastExpenseHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\ForecastExpense'

    tavro.handler.forecast_revenues:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ForecastRevenueHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\ForecastRevenue'

    tavro.handler.forecast_staff_persons:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ForecastStaffPersonHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\ForecastStaffPerson'

    tavro.handler.metric:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\MetricHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Metric'

    tavro.handler.contacts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ContactHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Contact'

    tavro.handler.expenses:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\ExpenseHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_categories:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\ExpenseCategoryHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseCategory'

    tavro.handler.expense_tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseComment'

    tavro.handler.funding:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\FundingHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\FundingRound'

    tavro.handler.nodes:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\NodeHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Node'

    tavro.handler.node_tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeTag'

    tavro.handler.node_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeComment'

    tavro.handler.organizations:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\OrganizationHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Organization'

    tavro.handler.organization_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\OrganizationCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\OrganizationComment'

    tavro.handler.people:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\PersonHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Person'

    tavro.handler.products:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\ProductHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Product'

    tavro.handler.revenues:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\RevenueHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Revenue'

    tavro.handler.roles:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RoleHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Role'

    tavro.handler.services:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\ServiceHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Service'

    tavro.handler.service_categories:
        class: Tavro\Bundle\CoreBundle\Handler\AccountEntity\ServiceCategoryHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\ServiceCategory'

    tavro.handler.shareholders:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ShareholderHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Shareholder'

    tavro.handler.tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\TagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Tag'

    tavro.handler.users:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\UserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\User'

    tavro.handler.variables:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\VariableHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Variable'

# -------------------
# Image/File Handlers
# -------------------
    tavro.handler.files:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\FileHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\File'
            - '%file_bucket%'
            - '%amazon_s3_url%'

    tavro.handler.images:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ImageHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@event_dispatcher'
            - 'Tavro\Bundle\CoreBundle\Entity\Image'
            - '%file_bucket%'
            - '%amazon_s3_url%'