services:
    tavro.handler.accounts:
        class: Tavro\Bundle\CoreBundle\Handler\AccountHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Account'

    tavro.handler.account_users:
        class: Tavro\Bundle\CoreBundle\Handler\AccountUserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountUser'

    tavro.handler.account_groups:
        class: Tavro\Bundle\CoreBundle\Handler\AccountGroupHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountGroup'
    tavro.handler.account_group_users:
        class: Tavro\Bundle\CoreBundle\Handler\AccountGroupUserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountGroupUser'


    tavro.handler.comments:
        class: Tavro\Bundle\CoreBundle\Handler\CommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Comment'
    tavro.handler.comments:
        class: Tavro\Bundle\CoreBundle\Handler\CommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Comment'

    tavro.handler.revenue_comments:
        class: Tavro\Bundle\CoreBundle\Handler\RevenueCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\RevenueComment'

    tavro.handler.customer_comments:
        class: Tavro\Bundle\CoreBundle\Handler\OrganizationCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\OrganizationComment'

    tavro.handler.expense_comments:
        class: Tavro\Bundle\CoreBundle\Handler\ExpenseCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseComment'

    tavro.handler.node_comments:
        class: Tavro\Bundle\CoreBundle\Handler\NodeCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeComment'

    tavro.handler.contacts:
        class: Tavro\Bundle\CoreBundle\Handler\ContactHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Contact'

    tavro.handler.expenses:
        class: Tavro\Bundle\CoreBundle\Handler\ExpenseHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_categories:
        class: Tavro\Bundle\CoreBundle\Handler\ExpenseCategoryHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseCategory'

    tavro.handler.expense_tags:
        class: Tavro\Bundle\CoreBundle\Handler\ExpenseTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_comments:
        class: Tavro\Bundle\CoreBundle\Handler\ExpenseCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseComment'

    tavro.handler.funding:
        class: Tavro\Bundle\CoreBundle\Handler\FundingHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\FundingRound'

    tavro.handler.nodes:
        class: Tavro\Bundle\CoreBundle\Handler\NodeHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Node'

    tavro.handler.node_tags:
        class: Tavro\Bundle\CoreBundle\Handler\NodeTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeTag'

    tavro.handler.node_comments:
        class: Tavro\Bundle\CoreBundle\Handler\NodeCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeComment'

    tavro.handler.organizations:
        class: Tavro\Bundle\CoreBundle\Handler\OrganizationHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Organization'

    tavro.handler.people:
        class: Tavro\Bundle\CoreBundle\Handler\PersonHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Person'

    tavro.handler.products:
        class: Tavro\Bundle\CoreBundle\Handler\ProductHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Product'

    tavro.handler.revenues:
        class: Tavro\Bundle\CoreBundle\Handler\RevenueHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Revenue'

    tavro.handler.roles:
        class: Tavro\Bundle\CoreBundle\Handler\RoleHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Role'

    tavro.handler.services:
        class: Tavro\Bundle\CoreBundle\Handler\ServiceHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Service'

    tavro.handler.shareholders:
        class: Tavro\Bundle\CoreBundle\Handler\ShareholderHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Shareholder'

    tavro.handler.tags:
        class: Tavro\Bundle\CoreBundle\Handler\TagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Tag'

    tavro.handler.users:
        class: Tavro\Bundle\CoreBundle\Handler\UserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\User'
            - '@tavro.handler.people'

    tavro.handler.variables:
        class: Tavro\Bundle\CoreBundle\Handler\VariableHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Variable'

# -------------------
# Image/File Handlers
# -------------------

    tavro.handler.files:
        class: Tavro\Bundle\CoreBundle\Handler\FileHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\File'
            - '%file_bucket%'

    tavro.handler.images:
        class: Tavro\Bundle\CoreBundle\Handler\ImageHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Image'
            - '%image_bucket%'