services:
    tavro.handler.accounts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Account'

    tavro.handler.accounts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountUserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountUser'

    tavro.handler.accounts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountGroupHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountGroup'
    tavro.handler.accounts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\AccountGroupUserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\AccountGroupUser'


    tavro.handler.comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\CommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Comment'
    tavro.handler.comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\CommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Comment'

    tavro.handler.revenue_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RevenueCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\RevenueComment'

    tavro.handler.customer_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\OrganizationCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\OrganizationComment'

    tavro.handler.expense_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseComment'

    tavro.handler.node_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeComment'

    tavro.handler.contacts:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ContactHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Contact'

    tavro.handler.expenses:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_categories:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseCategoryHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseCategory'

    tavro.handler.expense_tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseComment'

    tavro.handler.funding:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\FundingHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\FundingRound'

    tavro.handler.nodes:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Node'

    tavro.handler.node_tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeTag'

    tavro.handler.node_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeComment'

    tavro.handler.organizations:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\OrganizationHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Organization'

    tavro.handler.people:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\PersonHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Person'

    tavro.handler.products:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ProductHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Product'

    tavro.handler.revenues:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RevenueHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Revenue'

    tavro.handler.roles:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RoleHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Role'

    tavro.handler.services:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ServiceHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Service'

    tavro.handler.shareholders:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ShareholderHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Shareholder'

    tavro.handler.tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\TagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Tag'

    tavro.handler.users:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\UserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\User'
            - '@tavro.handler.people'

    tavro.handler.user_quickbooks:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\UserQuickbooksHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\UserQuickbooks'

    tavro.handler.user_organizations:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\UserOrganizationHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\UserOrganization'

    tavro.handler.variables:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\VariableHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Variable'

# -------------------
# Image/File Handlers
# -------------------

#    tavro.handler.files:
#        class: Tavro\Bundle\CoreBundle\Handler\Entity\FileHandler
#        arguments:
#            - '@doctrine.orm.main_entity_manager'
#            - '@form.factory'
#            - '@validator'
#            - '@security.encoder_factory.generic'
#            - '@security.token_storage'
#            - '@security.authorization_checker'
#            - '%amazon_s3_url%'
#            - 'Tavro\Bundle\CoreBundle\Entity\File'

    tavro.handler.images:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ImageHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Image'