services:
    tavro.handler.comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\CommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Comment'

    tavro.handler.customers:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\CustomerHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Customer'

    tavro.handler.expenses:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_categories:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseCategoryHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseCategory'

    tavro.handler.expense_tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Expense'

    tavro.handler.expense_comments:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ExpenseCommentHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\ExpenseComment'

    tavro.handler.funding:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\FundingHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\FundingRound'

    tavro.handler.nodes:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Node'

    tavro.handler.node_tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\NodeTagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\NodeTag'

    tavro.handler.organizations:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\OrganizationHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Organization'

    tavro.handler.products:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ProductHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Product'

    tavro.handler.revenues:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RevenueHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Revenue'

    tavro.handler.roles:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\RoleHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Role'

    tavro.handler.services:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ServiceHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Service'

    tavro.handler.shareholders:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ShareholderHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Shareholder'

    tavro.handler.tags:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\TagHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Tag'

    tavro.handler.users:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\UserHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\User'

    tavro.handler.user_organizations:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\UserOrganizationHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\UserOrganization'

    tavro.handler.variables:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\VariableHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Variable'

# -------------------
# Image/File Handlers
# -------------------

#    tavro.handler.files:
#        class: Tavro\Bundle\CoreBundle\Handler\Entity\FileHandler
#        arguments:
#            - '@doctrine.orm.main_entity_manager'
#            - '@form.factory'
#            - '@validator'
#            - '@security.encoder_factory.generic'
#            - '@security.token_storage'
#            - '@security.authorization_checker'
#            - '%amazon_s3_url%'
#            - 'Tavro\Bundle\CoreBundle\Entity\File'

    tavro.handler.images:
        class: Tavro\Bundle\CoreBundle\Handler\Entity\ImageHandler
        arguments:
            - '@doctrine.orm.main_entity_manager'
            - '@form.factory'
            - '@validator'
            - '@security.encoder_factory.generic'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%amazon_s3_url%'
            - 'Tavro\Bundle\CoreBundle\Entity\Image'