services:

# =======================================
# LISTENERS / AUTHENTICATORS / PROVIDERS
# =======================================

    tavro.api_authenticator:
        class: Tavro\Bundle\CoreBundle\Security\Authentication\Authenticator\ApiAuthenticator
        arguments: ['@doctrine.orm.entity_manager']

    tavro.password_encoder:
        class: Tavro\Bundle\CoreBundle\Security\Encoder\PasswordEncoder

    tavro.user_provider:
        class: Tavro\Bundle\CoreBundle\Security\Authentication\Provider\UserProvider
        arguments: ["@doctrine.orm.main_entity_manager"]

    tavro.user_authenticator:
        class:     Tavro\Bundle\CoreBundle\Security\Authentication\Authenticator\UserAuthenticator
        arguments: ["@tavro.password_encoder", "@tavro.user_provider"]

    tavro.listener.logout:
        class:  Tavro\Bundle\CoreBundle\EventListener\Security\LogoutListener
        arguments:  ["@security.token_storage"]

    tavro.listener.login:
        class: Tavro\Bundle\CoreBundle\EventListener\Security\LoginListener
        arguments: ["@security.authorization_checker", "@router", "@doctrine.orm.entity_manager"]

# ==============
# ENTITY VOTERS
# ==============

    tavro.voter.comment:
        class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\CommentVoter
        public:     false
        tags:
            - { name: security.voter }

    tavro.voter.user:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\UserVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.role:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RoleVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.node:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\NodeVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.image:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ImageVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.file:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\FileVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.tag:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\TagVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.node_tag:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\NodeTagVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.user_organization:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\UserOrganizationVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.organization:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\OrganizationVoter
         public:     false
         arguments: ['@security.access.decision_manager']
         tags:
             - { name: security.voter }

    tavro.voter.customer_comment:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\CustomerCommentVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.customer:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\CustomerVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.expense_category:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ExpenseCategoryVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.expense_comment:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ExpenseCommentVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.expense_tag:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ExpenseTagVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.expense:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ExpenseVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.funding_round_comment:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\FundingRoundCommentVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.funding_round_shareholder:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\FundingRoundShareholderVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.funding_round:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\FundingRoundVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.node_comment:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\NodeCommentVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.node_read:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\NodeReadVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.product_category:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ProductCategoryVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.product_image:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ProductImageVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.product:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ProductVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.revenue_category:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RevenueCategoryVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.revenue_comment:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RevenueCommentVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.revenue_product:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RevenueProductVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.revenue_service:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RevenueServiceVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.revenue_tag:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RevenueTagVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.revenue:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\RevenueVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.service_category:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ServiceCategoryVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.service:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\ServiceVoter
         public:     false
         tags:
             - { name: security.voter }

    tavro.voter.user_quickbooks:
         class:      Tavro\Bundle\CoreBundle\Security\Voter\Entity\UserQuickbooksVoter
         public:     false
         tags:
             - { name: security.voter }