services:

# =======================================
# LISTENERS / AUTHENTICATORS / PROVIDERS
# =======================================

    tavro.password_encoder:
        class: Tavro\Bundle\CoreBundle\Services\PasswordEncoder

    tavro.user_provider:
        class: Tavro\Bundle\CoreBundle\Security\UserProvider
        arguments: ["@doctrine.orm.main_entity_manager"]

    tavro.user_authenticator:
        class:     Tavro\Bundle\CoreBundle\Security\UserAuthenticator
        arguments: ["@tavro.password_encoder", "@tavro.user_provider"]

    tavro.logout_listener:
        class:  Tavro\Bundle\CoreBundle\EventListener\LogoutListener
        arguments:  ["@security.token_storage"]

    tavro.login_listener:
        class: Tavro\Bundle\CoreBundle\EventListener\LoginListener
        arguments: ["@security.authorization_checker", "@router"]

# ==============
# ENTITY VOTERS
# ==============

    tavro.voter.comment:
        class:      Tavro\Bundle\CoreBundle\Voter\CommentVoter
        public:     false
        tags:
            - { name: security.voter }
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.voter.user:
         class:      Tavro\Bundle\CoreBundle\Voter\UserVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
             - [ setContainer, [ '@service_container' ] ]

    tavro.voter.role:
         class:      Tavro\Bundle\CoreBundle\Voter\RoleVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
             - [ setContainer, [ '@service_container' ] ]

    tavro.voter.node:
         class:      Tavro\Bundle\CoreBundle\Voter\NodeVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.voter.image:
         class:      Tavro\Bundle\CoreBundle\Voter\ImageVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
             - [ setContainer, [ '@service_container' ] ]

    tavro.voter.file:
         class:      Tavro\Bundle\CoreBundle\Voter\FileVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
             - [ setContainer, [ '@service_container' ] ]

    tavro.voter.tag:
         class:      Tavro\Bundle\CoreBundle\Voter\TagVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
             - [ setContainer, [ '@service_container' ] ]

    tavro.voter.node_tag:
         class:      Tavro\Bundle\CoreBundle\Voter\NodeTagVoter
         public:     false
         tags:
             - { name: security.voter }
         calls:
             - [ setContainer, [ '@service_container' ] ]