services:

    tavro.mailer:
        class: Tavro\Bundle\CoreBundle\Mail\TavroMailer
        arguments: ["@mailer", "@templating"]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.quickbooks:
        class: Tavro\Bundle\CoreBundle\Handler\Quickbookshandler
        arguments: ["@mailer", "@templating"]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.freshbooks:
        class: Tavro\Bundle\CoreBundle\Handler\FreshbooksHandler
        arguments: ["@mailer", "@templating"]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.file_manager:
        class: Tavro\Bundle\CoreBundle\Aws\S3\FileManager
        arguments: ["%aws_access_key_id%", "%aws_secret_access_key%", %aws_s3_region% ]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.dbal:
        class: Tavro\Bundle\CoreBundle\Doctrine\Dbal\Dbal
        arguments: []
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro_serializer:
        class: Tavro\Bundle\CoreBundle\Serializer\Serializer
        arguments: ["@serializer"]

    tavro.listener.request:
        class: Tavro\Bundle\CoreBundle\EventListener\Request\RequestListener
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2 }

    tavro.subscriber.exception:
        class: Tavro\Bundle\CoreBundle\EventSubscriber\Exception\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["%kernel.debug%", "@serializer"]

    tavro.subscriber.user:
        class: Tavro\Bundle\CoreBundle\EventSubscriber\TavroUser\UserSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["@tavro.mailer"]