services:

    tavro.mailer:
        class: Tavro\Bundle\CoreBundle\Mail\TavroMailer
        arguments: ["@mailer", "@logger", "@templating"]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.file_manager:
        class: Tavro\Bundle\CoreBundle\Aws\S3\FileManager
        arguments: ["%aws_access_key_id%", "%aws_secret_access_key%", "%aws_s3_region%" ]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.dbal:
        class: Tavro\Bundle\CoreBundle\Doctrine\Dbal\Dbal
        arguments: []
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.security_handler:
        class: Tavro\Bundle\CoreBundle\Handler\SecurityHandler
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.date_handler:
        class: Tavro\Bundle\CoreBundle\Handler\DateHandler
        arguments: ["%timezone%"]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro_serializer:
        class: Tavro\Bundle\CoreBundle\Serializer\Serializer
        arguments: ["@serializer"]

    tavro.listener.request:
        class: Tavro\Bundle\CoreBundle\EventListener\Request\RequestListener
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2 }

    tavro.subscriber.user:
        class: Tavro\Bundle\CoreBundle\EventSubscriber\User\UserSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["@tavro.mailer", "@logger", "%app_email%", "%app_email_name%"]

#    tavro.push_notifications:
#        class: Tavro\Bundle\CoreBundle\Notifications\NotificationHandler
#        arguments: ["@tavro.aws_sns", "@logger"]

    tavro.logging.exception:
        class: Tavro\Bundle\CoreBundle\Logging\Exception\TavroExceptionLogger
        arguments: ["@logger"]

    tavro.twig.extension:
        class: Tavro\Bundle\CoreBundle\Twig\Extensions\TavroConfigExtension
        properties:
          container: "@service_container"
        tags:
          - { name: twig.extension }