services:

    tavro.user_activity_listener:
          class: Tavro\Bundle\CoreBundle\EventListener\UserActivityListener
          arguments: ["@security.token_storage", "@doctrine.orm.main_entity_manager"]
          tags:
              - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    tavro.mailer:
        class: Tavro\Bundle\CoreBundle\Services\TavroMailer
        arguments: ["@mailer", "@templating"]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.validator:
        class: Tavro\Bundle\CoreBundle\Services\TavroValidator
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.file_manager:
        class: Tavro\Bundle\CoreBundle\Services\FileManager
        arguments: ["%aws_access_key_id%", "%aws_secret_access_key%", %aws_s3_region% ]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro.dbal:
        class: Tavro\Bundle\CoreBundle\Services\Dbal
        arguments: []
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tavro_serializer:
        class: Tavro\Bundle\CoreBundle\Services\Serializer
        arguments: ["@serializer"]

    tavro.listener.request:
        class: Tavro\Bundle\CoreBundle\EventListener\Request\RequestListener
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2 }

    tavro.subscriber.exception:
        class: Tavro\Bundle\CoreBundle\EventSubscriber\Exception\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }