api_get_account_users:
    path: /accounts/{account}/users.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\AccountUser:getAll, _format: json}
    methods: GET
    requirements:
        account: \d+
        _format: json|xml

api_get_account_user:
    path: /accounts/{account}/users.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\AccountUser:get, _format: json}
    methods: GET
    requirements:
        account: \d+
        _format: json|xml

api_post_account_user:
    path: /accounts/{account}/users.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\AccountUser:post, _format: json}
    methods: POST
    requirements:
        account: \d+
        _format: json|xml

api_delete_account_user:
    path:  /account_users/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\AccountUser:delete, _format: json, entity: "accounts" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml