api_get_forecast:
    path: /forecasts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:get, _format: json, entity: "forecasts" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_forecasts:
    path:  /forecasts.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:getAllByAccount, _format: json, entity: "forecasts" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_forecast:
    path:  /forecasts.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:post, _format: json, entity: "forecasts" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_forecast:
    path:  /forecasts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:patch, _format: json, entity: "forecasts" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_forecast:
    path:  /forecasts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:put, _format: json, entity: "forecasts" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_forecast:
    path:  /forecasts/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:delete, _format: json, entity: "forecasts" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_delete_forecast_tag:
    path:  /forecasts/{forecast}/tags/{tag}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:deleteTag, _format: json }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_forecasts:
    path:  /typeahead/forecasts.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml

api_forecast_comments:
    path: /forecasts/{forecast}/comments.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_forecast_comment:
    path: /forecasts/{forecast}/comments.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Forecast:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml