api_get_organization:
    path: /organizations/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:get, _format: json, entity: "organizations" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_organizations:
    path:  /organizations.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:getAllByAccount, _format: json, entity: "organizations" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_organization:
    path:  /organizations.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:post, _format: json, entity: "organizations" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:patch, _format: json, entity: "organizations" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:put, _format: json, entity: "organizations" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:delete, _format: json, entity: "organizations" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_organizations:
    path:  /typeahead/organizations.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:typeahead, _format: json }
    methods: GET
    requirements:
        _format:  json|xml
        
api_organization_tags:
    path: /organizations/{organization}/tags.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:tags, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_organization_tag:
    path: /organizations/{organization}/tags.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:newTag, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml

api_organization_comments:
    path: /organizations/{organization}/comments.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:comments, _format: json}
    methods: GET
    requirements:
        organization: \d+
        _format: json|xml

api_new_organization_comment:
    path: /organizations/{organization}/comments.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Organization:newComment, _format: json}
    methods: POST
    requirements:
        organization: \d+
        _format: json|xml