api_get_product:
    path: /products/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:get, _format: json, entity: 'products' }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_product_images:
    path:  /products/{id}/images.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:getImages, _format: json, entity: 'products' }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_product_image:
    path:  /products/{product}/images.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:newImage, _format: json, entity: 'products' }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_get_all_products:
    path:  /products.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:getAllByAccount, _format: json, entity: 'products' }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_product:
    path:  /products.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:post, _format: json, entity: 'products' }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_product:
    path:  /products/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:patch, _format: json, entity: 'products' }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_product:
    path:  /products/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:put, _format: json, entity: 'products' }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_product:
    path:  /products/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:delete, _format: json, entity: 'products' }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_products:
    path:  /typeahead/products.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\Product:typeahead, _format: json }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml