api_get_service_category:
    path: /service_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ServiceCategory:get, _format: json, entity: "service_categories" }
    methods: GET
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_service_categories:
    path:  /service_categories.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ServiceCategory:getAllByAccount, _format: json, entity: "service_categories" }
    methods: GET
    requirements:
        _format:  json|xml

api_post_service_category:
    path:  /service_categories.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ServiceCategory:post, _format: json, entity: "service_categories" }
    methods: POST
    requirements:
        _format:  json|xml

api_patch_service_category:
    path:  /service_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ServiceCategory:patch, _format: json, entity: "service_categories" }
    methods: PATCH
    requirements:
        id: \d+
        _format:  json|xml

api_put_service_category:
    path:  /service_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ServiceCategory:put, _format: json, entity: "service_categories" }
    methods: PUT
    requirements:
        id: \d+
        _format:  json|xml

api_delete_service_category:
    path:  /service_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ServiceCategory:delete, _format: json, entity: "service_categories" }
    methods: DELETE
    requirements:
        id: \d+
        _format:  json|xml