<?php

namespace Tavro\Bundle\CoreBundle\Repository\Entity;

/**
 * ServiceImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceImageRepository extends \Doctrine\ORM\EntityRepository
{
}
