admin:
    path: /admin
    defaults: { _controller: TavroAppBundle:Admin:index }

admin_user_dev_requests:
    path: /admin/user/dev
    defaults: { _controller: TavroAppBundle:Admin:userDevRequests }

admin_mods:
    path: /admin/mods
    defaults: { _controller: TavroAppBundle:Admin:mods }

admin_users:
    path: /admin/users
    defaults: { _controller: TavroAppBundle:Admin:users }

admin_nodes:
    path: /admin/nodes
    defaults: { _controller: TavroAppBundle:Admin:nodes }

admin_node_new:
    path: /admin/nodes/new
    defaults: { _controller: TavroAppBundle:Admin:newNode }