ajax_summary:
    path: /{group}/core.{_format}
    defaults: { _controller: TavroAppBundle:Ajax:summary, _format: json }
    methods: GET
    requirements:
        group: "(api|tavro|summary)"
        _format:  json|xml

user_roles:
    path: /{group}/{user}/roles.{_format}
    defaults: { _controller: TavroAppBundle:Ajax:roles, _format: json }
    methods: GET
    requirements:
        group: "(api|tavro|summary)"
        user: \d+
        _format:  json|xml
