api_doc_index:
    path: /getting-started
    defaults: { _controller: "TavroAppBundle:Documentation:index" }
api_doc_user:
    path: /user
    defaults: { _controller: "TavroAppBundle:Documentation:user" }
api_doc_organization:
    path: /organization
    defaults: { _controller: "TavroAppBundle:Documentation:organization" }
api_doc_expense:
    path: /expense
    defaults: { _controller: "TavroAppBundle:Documentation:expense" }
api_doc_funding:
    path: /funding
    defaults: { _controller: "TavroAppBundle:Documentation:funding" }
api_doc_node:
    path: /node
    defaults: { _controller: "TavroAppBundle:Documentation:node" }
api_doc_product:
    path: /product
    defaults: { _controller: "TavroAppBundle:Documentation:product" }
api_doc_revenue:
    path: /revenue
    defaults: { _controller: "TavroAppBundle:Documentation:revenue" }
api_doc_service:
    path: /service
    defaults: { _controller: "TavroAppBundle:Documentation:service" }
api_doc_shareholder:
    path: /shareholder
    defaults: { _controller: "TavroAppBundle:Documentation:shareholder" }
api_doc_comment:
    path: /comment
    defaults: { _controller: "TavroAppBundle:Documentation:comment" }