<?php

namespace Tavro\Bundle\CoreBundle\Doctrine\Repository\Entity;

use Doctrine\ORM\EntityRepository;
use Tavro\Bundle\CoreBundle\Services\Repository\TavroRepository;

/**
 * NodeReadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeReadRepository extends EntityRepository
{
}
