api_get_account_users:
    path: /users.{_format}
    defaults: { _controller: AccountEntity\AccountUser:getAllByAccount, _format: json, entity: "account_users" }
    methods: [GET|OPTIONS]
    requirements:
        account: \d+
        _format: json|xml

api_get_account_user:
    path: /account_users/{id}.{_format}
    defaults: { _controller: AccountEntity\AccountUser:get, _format: json, entity: "account_users" }
    methods: [GET|OPTIONS]
    requirements:
        account: \d+
        _format: json|xml

api_post_account_user:
    path: /users.{_format}
    defaults: { _controller: AccountEntity\AccountUser:post, _format: json, entity: "account_users" }
    methods: [POST|OPTIONS]
    requirements:
        account: \d+
        _format: json|xml

api_delete_account_user:
    path:  /account_users/{id}.{_format}
    defaults: { _controller: AccountEntity\AccountUser:delete, _format: json, entity: "account_users" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml