api_get_forecast:
    path: /forecasts/{id}.{_format}
    defaults: { _controller: AccountEntity\Forecast:get, _format: json, entity: "forecasts" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_forecasts:
    path:  /forecasts.{_format}
    defaults: { _controller: AccountEntity\Forecast:getAllByAccount, _format: json, entity: "forecasts" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_forecast:
    path:  /forecasts.{_format}
    defaults: { _controller: AccountEntity\Forecast:post, _format: json, entity: "forecasts" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_forecast:
    path:  /forecasts/{id}.{_format}
    defaults: { _controller: AccountEntity\Forecast:patch, _format: json, entity: "forecasts" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_forecast:
    path:  /forecasts/{id}.{_format}
    defaults: { _controller: AccountEntity\Forecast:put, _format: json, entity: "forecasts" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_forecast:
    path:  /forecasts/{id}.{_format}
    defaults: { _controller: AccountEntity\Forecast:delete, _format: json, entity: "forecasts" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_forecast_tag:
    path:  /forecasts/{forecast}/tags/{tag}.{_format}
    defaults: { _controller: AccountEntity\Forecast:deleteTag, _format: json }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_forecasts:
    path:  /typeahead/forecasts.{_format}
    defaults: { _controller: AccountEntity\Forecast:typeahead, _format: json }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_forecast_comments:
    path: /forecasts/{forecast}/comments.{_format}
    defaults: { _controller: AccountEntity\Forecast:comments, _format: json}
    methods: [GET|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml

api_new_forecast_comment:
    path: /forecasts/{forecast}/comments.{_format}
    defaults: { _controller: AccountEntity\Forecast:newComment, _format: json}
    methods: [POST|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml