api_get_product_category:
    path: /product_categories/{id}.{_format}
    defaults: { _controller: AccountEntity\ProductCategory:get, _format: json, entity: "product_categories" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_product_categories:
    path:  /product_categories.{_format}
    defaults: { _controller: AccountEntity\ProductCategory:getAllByAccount, _format: json, entity: "product_categories" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_product_category:
    path:  /product_categories.{_format}
    defaults: { _controller: AccountEntity\ProductCategory:post, _format: json, entity: "product_categories" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_product_category:
    path:  /product_categories/{id}.{_format}
    defaults: { _controller: AccountEntity\ProductCategory:patch, _format: json, entity: "product_categories" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_product_category:
    path:  /product_categories/{id}.{_format}
    defaults: { _controller: AccountEntity\ProductCategory:put, _format: json, entity: "product_categories" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_product_category:
    path:  /product_categories/{id}.{_format}
    defaults: { _controller: AccountEntity\ProductCategory:delete, _format: json, entity: "product_categories" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml