api_get_organization:
    path: /organizations/{id}.{_format}
    defaults: { _controller: AccountEntity\Organization:get, _format: json, entity: "organizations" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_organizations:
    path:  /organizations.{_format}
    defaults: { _controller: AccountEntity\Organization:getAllByAccount, _format: json, entity: "organizations" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_organization:
    path:  /organizations.{_format}
    defaults: { _controller: AccountEntity\Organization:post, _format: json, entity: "organizations" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: AccountEntity\Organization:patch, _format: json, entity: "organizations" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: AccountEntity\Organization:put, _format: json, entity: "organizations" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_organization:
    path:  /organizations/{id}.{_format}
    defaults: { _controller: AccountEntity\Organization:delete, _format: json, entity: "organizations" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_organizations:
    path:  /typeahead/organizations.{_format}
    defaults: { _controller: AccountEntity\Organization:typeahead, _format: json }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml
        
api_organization_tags:
    path: /organizations/{organization}/tags.{_format}
    defaults: { _controller: AccountEntity\Organization:tags, _format: json}
    methods: [GET|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml

api_new_organization_tag:
    path: /organizations/{organization}/tags.{_format}
    defaults: { _controller: AccountEntity\Organization:newTag, _format: json}
    methods: [POST|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml

api_organization_comments:
    path: /organizations/{organization}/comments.{_format}
    defaults: { _controller: AccountEntity\Organization:comments, _format: json}
    methods: [GET|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml

api_new_organization_comment:
    path: /organizations/{organization}/comments.{_format}
    defaults: { _controller: AccountEntity\Organization:newComment, _format: json}
    methods: [POST|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml