api_get_service:
    path: /services/{id}.{_format}
    defaults: { _controller: AccountEntity\Service:get, _format: json, entity: 'services' }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_services:
    path:  /services.{_format}
    defaults: { _controller: AccountEntity\Service:getAllByAccount, _format: json, entity: 'services' }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_service:
    path:  /services.{_format}
    defaults: { _controller: AccountEntity\Service:post, _format: json, entity: 'services' }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_service:
    path:  /services/{id}.{_format}
    defaults: { _controller: AccountEntity\Service:patch, _format: json, entity: 'services' }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_service:
    path:  /services/{id}.{_format}
    defaults: { _controller: AccountEntity\Service:put, _format: json, entity: 'services' }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_service:
    path:  /services/{id}.{_format}
    defaults: { _controller: AccountEntity\Service:delete, _format: json, entity: 'services' }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_services:
    path:  /typeahead/services.{_format}
    defaults: { _controller: AccountEntity\Service:typeahead, _format: json }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml
