imports:
    - { resource: config.yml }

framework:
    templating:
        engines: ['twig']
    test: ~

swiftmailer:
    disable_delivery:  true

lexik_jwt_authentication:
    pass_phrase: "%jwt_token_passphrase%"
    token_ttl: "%jwt_token_ttl%"
    public_key_path: "%kernel.root_dir%/keys/public.pem"
    private_key_path: "%kernel.root_dir%/keys/private.pem"