lexik_jwt_authentication:
    pass_phrase: '%env(JWT_TOKEN_PASSPHRASE)%'
    token_ttl: '%env(JWT_TOKEN_TTL)%'
    public_key_path: "%kernel.root_dir%/var/keys/public.pem"
    private_key_path: "%kernel.root_dir%/var/keys/private.pem"