---
- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: Update apt
  apt: update_cache=yes

- name: install nginx + packages
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx

- name: create sites-available
  file: path=/etc/nginx/sites-available state=directory

- name: create sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory

- name: copy api config
  template: src=api.conf.j2 dest=/etc/nginx/sites-available/api.conf owner=www-data group=www-data mode=0644

- name: copy admin config
  template: src=admin.conf.j2 dest=/etc/nginx/sites-available/admin.conf owner=www-data group=www-data mode=0644

- name: copy app config
  template: src=app.conf.j2 dest=/etc/nginx/sites-available/app.conf owner=www-data group=www-data mode=0644

- name: copy docs config
  template: src=docs.conf.j2 dest=/etc/nginx/sites-available/docs.conf owner=www-data group=www-data mode=0644

- name: copy phpunit config
  template: src=phpunit.conf.j2 dest=/etc/nginx/sites-available/phpunit.conf owner=www-data group=www-data mode=0644

- name: enable api vhost
  file:
    src: /etc/nginx/sites-available/api.conf
    dest: /etc/nginx/sites-enabled/api.conf
    state: link

- name: enable admin vhost
  file:
    src: /etc/nginx/sites-available/admin.conf
    dest: /etc/nginx/sites-enabled/admin.conf
    state: link

- name: enable app vhost
  file:
    src: /etc/nginx/sites-available/app.conf
    dest: /etc/nginx/sites-enabled/app.conf
    state: link

- name: enable docs vhost
  file:
    src: /etc/nginx/sites-available/docs.conf
    dest: /etc/nginx/sites-enabled/docs.conf
    state: link

- name: enable phpunit vhost
  file:
    src: /etc/nginx/sites-available/phpunit.conf
    dest: /etc/nginx/sites-enabled/phpunit.conf
    state: link

- name: mimic apache config loaders for nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=www-data group=www-data mode=0644

- name: update fpm port
  lineinfile: state=present dest="/etc/php/7.0/fpm/pool.d/www.conf" regexp="^listen = /run/php/php7.0-fpm.sock" line="listen = 127.0.0.1:9000"

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started