imports:
    - { resource: config.yml }

parameters:
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: false
    delivery_address: jake.litwicki@gmail.com

lexik_jwt_authentication:
    pass_phrase: %jwt_token_passphrase%
    token_ttl: %jwt_token_ttl%
    public_key_path: '%kernel.root_dir%/keys/public.pem'
    private_key_path: '%kernel.root_dir%/keys/private.pem'