imports:
    - { resource: config.yml }

parameters:
    assetic.filter.compass.images_dir: "%kernel.root_dir%/../web/images"
    assetic.filter.compass.http_path:  /images

monolog:
    use_microseconds: false

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true

swiftmailer:
    delivery_addresses: ['%debug_email%']
    delivery_whitelist:
       - '/[^dev]@zoadilack\.com$/'
       - '/^@tavro\.io/'

lexik_jwt_authentication:
    pass_phrase: "%jwt_token_passphrase%"
    token_ttl: "%jwt_token_ttl%"
    public_key_path: "%kernel.root_dir%/keys/public.pem"
    private_key_path: "%kernel.root_dir%/keys/private.pem"

nelmio_cors: ~

services:

    tavro_api.subscriber.exception:
        class: Tavro\Bundle\ApiBundle\EventSubscriber\Exception\Dev\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["@tavro_serializer", "@tavro.logging.exception"]