imports:
    - { resource: config.yml }

parameters:
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

# Monolog Configuration
monolog:
    handlers:
        logentries:
            type: service
            id: '@monolog.handler.logentries'
            level: debug
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    cache:  false
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        app_version: %app_version%
        app_hostname: %app_hostname%
        api_hostname: %api_hostname%
        app_email: %app_email%
        app_email_name: %app_email_name%
        app_debug: %kernel.debug%
        amazon_s3_url: %amazon_s3_url%
        asset_bucket: %asset_bucket%
        qbo_request_token_uri: %qbo_request_token_uri%
        qbo_access_token_uri: %qbo_access_token_uri%
        qbo_request_uri: %qbo_request_uri%

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: false
    delivery_address: jake.litwicki@gmail.com

lexik_jwt_authentication:
    pass_phrase: %jwt_token_passphrase%
    token_ttl: %jwt_token_ttl%
    public_key_path: '%kernel.root_dir%/keys/public.pem'
    private_key_path: '%kernel.root_dir%/keys/private.pem'