# ======================================
# APPLICATION FRONTEND (ANGULAR et-all)
# ======================================
tavro_api_app:
    host: %api_hostname%
    resource: "@TavroAppBundle/Resources/config/routing.yml"
    requirements:
        api_host: ^(api_hostname%|api.localhost)$
    defaults:
        api_host: %api_hostname%

tavro_api:
    host: %api_hostname%
    resource: "@TavroApiBundle/Resources/config/routing.yml"
    requirements:
        api_host: ^(api_hostname%|api.localhost)$
    defaults:
        api_host: %api_hostname%
    prefix: /api/v1

# =======================
# CONTRIB BUNDLE ROUTING
# =======================
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"