# ======================================
# APPLICATION FRONTEND (ANGULAR et-all)
# ======================================
tavro_core:
    host: %api_hostname%
    resource: "@TavroCoreBundle/Resources/config/routing.yml"
    requirements:
        api_host: ^(api_hostname%|api.localhost)$
    defaults:
        api_host: %api_hostname%

tavro_api:
    host: %api_hostname%
    resource: "@TavroApiBundle/Resources/config/routing.yml"
    requirements:
        api_host: ^(api_hostname%|api.localhost)$
    defaults:
        api_host: %api_hostname%
    prefix: /api/v1

tavro_admin:
    resource: "@TavroAdminBundle/Resources/config/routing.yml"
    requirements:
        api_host: ^(admin_hostname%|admin.localhost)$
    defaults:
        api_host: %admin_hostname%

# =======================
# CONTRIB BUNDLE ROUTING
# =======================
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"