_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
_main:
    resource: routing.yml
_index:
    resource: "@TavroApiBundle/Resources/config/routing_dev.yml"