security:
    role_hierarchy:
        ROLE_API: [ROLE_USER]
        ROLE_DEVELOPER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_API,ROLE_DEVELOPER]
        ROLE_SUPERUSER: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Tavro\Bundle\CoreBundle\Entity\User
                property: username
        api_key_user_provider:
            id: tavro.user_provider

    encoders:
        Tavro\Bundle\CoreBundle\Entity\User:
             id: tavro.password_encoder
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            host: %api_hostname%
            pattern: ^/docs
            anonymous: ~
            provider: main
            simple_form:
                authenticator: tavro.user_authenticator
                check_path: login_check
                login_path: login
                remember_me: true
                always_use_default_target_path: false
                success_handler: tavro.login_listener
                failure_path:   /user/login
            logout:
                path: /user/logout
                target: /
                success_handler: tavro.logout_listener
            remember_me:
                secret: "%secret%"
                lifetime: 25920000 # 30 days
                #lifetime: 31536000 # 365 days
                path: /

        api:
            host: %api_hostname%
            pattern: ^/api
            anonymous: ~
            guard:
                authenticators:
                    - tavro.token_authenticator

    access_control:
        - { path: ^/user, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Leave last!

        - { path: ^/, roles: [ROLE_USER] }