security:
    role_hierarchy:
        ROLE_API: [ROLE_USER]
        ROLE_DEVELOPER: [ROLE_USER]
        ROLE_CSE: [ROLE_USER]
        ROLE_CONTRIBUTOR: [ROLE_USER]
        ROLE_MODERATOR: [ROLE_USER]
        ROLE_ADMIN: [ROLE_API,ROLE_MODERATOR,ROLE_CONTRIBUTOR,ROLE_DEVELOPER]
        ROLE_SUPERUSER: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Tavro\Bundle\CoreBundle\Entity\User
                property: username
        api_key_user_provider:
            id: tavro.user_provider

    encoders:
        Tavro\Bundle\CoreBundle\Entity\User:
             id: tavro.password_encoder
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_v1:
            #host: %api_hostname%
            pattern: ^/api
            anonymous: ~
            provider: api_key_user_provider
            stateless: true
            #http_basic: ~
            simple_preauth:
                authenticator: tavro.angular_api_authenticator

        api_v2:
            host: %api_hostname%
            pattern: ^/api
            anonymous: ~
            provider: api_key_user_provider
            stateless: true
            simple_preauth:
                authenticator: tavro.api_authenticator

        main:
            host: %app_hostname%
            pattern: ^/
            anonymous: ~
            provider: main
            simple_form:
                authenticator: tavro.user_authenticator
                check_path: login_check
                login_path: login
                remember_me: true
                always_use_default_target_path: false
                success_handler: tavro.login_listener
                failure_path:   /login
            logout:
                path: /logout
                target: /
                success_handler: tavro.logout_listener
            remember_me:
                secret: "%secret%"
                lifetime: 25920000 # 30 days
                #lifetime: 31536000 # 365 days
                path: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile$, role: ROLE_USER }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/admin, role: ROLE_ADMIN }

        # Leave last!
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }