parameters: ~
services:
    wsse.security.authentication.provider:
        class: Tavro\Bundle\CoreBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - '' # User Provider
            - '%kernel.cache_dir%/security/nonces'
        public: false

    wsse.security.authentication.listener:
        class: Tavro\Bundle\CoreBundle\Security\Firewall\WsseListener
        arguments: ['@security.token_storage', '@security.authentication.manager']
        public: false

    tavro.token_authenticator:
        class: Tavro\Bundle\CoreBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']