---
- hosts: all
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  roles:
    - role: server
    - role: composer
    - role: nginx
    - role: mysql
    - role: phpunit
    - role: vagrant_local
    - role: app