---
- hosts: all

  become: true
  become_user: root

  vars:
    api_root: "/var/www/tavro/api/"
    fixture_path: "src/Tavro/Bundle/CoreBundle/DataFixtures/"
    core_fixture_name: "Core"
    demo_fixture_name: "Demo"

  tasks:
    - name: drop database
      shell: php {{api_root}}bin/console doctrine:database:drop --if-exists --force

    - name: recreate database
      shell: php {{api_root}}bin/console doctrine:database:create

    - name: execute migrations
      shell: php {{api_root}}bin/console doctrine:migrations:migrate --no-interaction

    - name: install core data
      shell: php {{api_root}}bin/console doctrine:fixtures:load --fixtures="{{api_root}}{{fixture_path}}{{core_fixture_name}}" --append

    - name: install demo data fixtures
      shell: php {{api_root}}bin/console doctrine:fixtures:load --fixtures="{{api_root}}{{fixture_path}}{{demo_fixture_name}}" --append

    - debug: msg="Demo Installation Complete on {{ inventory_hostname }}"