---
- hosts: all

  become: true
  become_user: root

  vars:
    api_root: "/var/www/tavro/api/"

  tasks:
    - name: Execute Unit Tests
      shell: php bin/console tavro:testing
      args:
          chdir: "{{api_root}}"

    - debug: msg="Tavro Unit Test Suite Complete!"