api_get_expense_category:
    path: /expense_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ExpenseCategory:get, _format: json, entity: "expense_categories" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_expense_categories:
    path:  /expense_categories.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ExpenseCategory:getAllByAccount, _format: json, entity: "expense_categories" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_expense_category:
    path:  /expense_categories.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ExpenseCategory:post, _format: json, entity: "expense_categories" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_expense_category:
    path:  /expense_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ExpenseCategory:patch, _format: json, entity: "expense_categories" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_expense_category:
    path:  /expense_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ExpenseCategory:put, _format: json, entity: "expense_categories" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_expense_category:
    path:  /expense_categories/{id}.{_format}
    defaults: { _controller: TavroApiBundle:AccountEntity\ExpenseCategory:delete, _format: json, entity: "expense_categories" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml