tavro_comment_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/comment.yml"

tavro_customer_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/customer.yml"

tavro_expense_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/expense.yml"

tavro_expense_category_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/expense_category.yml"

tavro_funding_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/funding.yml"

tavro_node_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/node.yml"

tavro_organization_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/organization.yml"

tavro_product_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/product.yml"

tavro_product_category_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/product_category.yml"

tavro_revenue_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/revenue.yml"

tavro_revenue_category_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/revenue_category.yml"

tavro_service_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/service.yml"

tavro_service_category_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/service_category.yml"

tavro_shareholder_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/shareholder.yml"

tavro_user_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/user.yml"

tavro_user_quickbooks_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/user_quickbooks.yml"

tavro_user_freshbooks_api:
    resource: "@TavroCoreBundle/Resources/config/routing/api/user_freshbooks.yml"