imports:
    - { resource: services/tavro.yml }
    - { resource: services/security.yml }
    - { resource: services/form.yml }

parameters:
    jms_serializer.json_serialization_visitor.class: Tavro\Bundle\CoreBundle\Services\JsonSerializationVisitor