tavro_user_mgmt_api:
    resource: "user.yml"

# --------------------------------------
#  Routes that require an Entity
# --------------------------------------
tavro_account_api:
    resource: "entity/account.yml"

tavro_account_type_api:
    resource: "entity/account_type.yml"

tavro_comment_api:
    resource: "entity/comment.yml"

tavro_contact_api:
    resource: "entity/contact.yml"

tavro_person_api:
    resource: "entity/person.yml"

tavro_shareholder_api:
    resource: "entity/shareholder.yml"

tavro_tag_api:
    resource: "entity/tag.yml"

tavro_user_api:
    resource: "entity/user.yml"

tavro_user_quickbooks_api:
    resource: "entity/user_quickbooks.yml"

tavro_user_freshbooks_api:
    resource: "entity/user_freshbooks.yml"

tavro_forecast_revenue_api:
    resource: "entity/forecast_revenue.yml"

tavro_forecast_expense_api:
    resource: "entity/forecast_expense.yml"

tavro_forecast_staff_api:
    resource: "entity/forecast_staff.yml"

# --------------------------------------
#  Routes that require an AccountEntity
# --------------------------------------
tavro_account_group_api:
    resource: "account-entity/account_group.yml"
    prefix: "accounts/{account}"

tavro_account_user_api:
    resource: "account-entity/account_user.yml"
    prefix: "accounts/{account}"

tavro_expense_api:
    resource: "account-entity/expense.yml"
    prefix: "accounts/{account}"

tavro_expense_category_api:
    resource: "account-entity/expense_category.yml"
    prefix: "accounts/{account}"

tavro_forecast_api:
    resource: "account-entity/forecast.yml"
    prefix: "accounts/{account}"

tavro_funding_api:
    resource: "account-entity/funding.yml"
    prefix: "accounts/{account}"

tavro_node_api:
    resource: "account-entity/node.yml"
    prefix: "accounts/{account}"

tavro_organization_api:
    resource: "account-entity/organization.yml"
    prefix: "accounts/{account}"

tavro_product_api:
    resource: "account-entity/product.yml"
    prefix: "accounts/{account}"

tavro_product_category_api:
    resource: "account-entity/product_category.yml"
    prefix: "accounts/{account}"

tavro_revenue_api:
    resource: "account-entity/revenue.yml"
    prefix: "accounts/{account}"

tavro_revenue_category_api:
    resource: "account-entity/revenue_category.yml"
    prefix: "accounts/{account}"

tavro_service_api:
    resource: "account-entity/service.yml"
    prefix: "accounts/{account}"

tavro_service_category_api:
    resource: "account-entity/service_category.yml"
    prefix: "accounts/{account}"
