api_user_reset_password:
    path: /auth/reset.{_format}
    defaults: { _controller: Security:reset, _format: json }
    methods: [POST|OPTIONS]

api_user_send_reset_password:
    path: /auth/forgot.{_format}
    defaults: { _controller: Security:sendResetToken, _format: json }
    methods: [POST|OPTIONS]

api_user_confirm_email:
    path: /auth/confirm.{_format}
    defaults: { _controller: Security:confirm, _format: json }
    methods: [POST|OPTIONS]

api_user_activate:
    path: /auth/activate.{_format}
    defaults: { _controller: Security:activate, _format: json }
    methods: [POST|OPTIONS]