api_get_forecast_staff:
    path: /forecasts/{forecast}/staff_persons.{_format}
    defaults: { _controller: Entity\ForecastStaffPerson:byForecast, _format: json}
    methods: [GET|OPTIONS]
    requirements:
        organization: \d+
        _format: json|xml