api_get_syndicate:
    path: /syndicates/{id}.{_format}
    defaults: { _controller: Entity\Node:get, _format: json, entity: "syndicates" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_syndicates:
    path:  /syndicates.{_format}
    defaults: { _controller: Entity\Node:getAll, _format: json, entity: "syndicates" }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_syndicate:
    path:  /syndicates.{_format}
    defaults: { _controller: Entity\Node:post, _format: json, entity: "syndicates" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_syndicate:
    path:  /syndicates/{id}.{_format}
    defaults: { _controller: Entity\Node:patch, _format: json, entity: "syndicates" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_syndicate:
    path:  /syndicates/{id}.{_format}
    defaults: { _controller: Entity\Node:put, _format: json, entity: "syndicates" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_syndicate:
    path:  /syndicates/{id}.{_format}
    defaults: { _controller: Entity\Node:delete, _format: json, entity: "syndicates" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml