api_get_tag:
    path: /tags/{id}.{_format}
    defaults: { _controller: Entity\Tag:get, _format: json, entity: 'tags' }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_get_all_tags:
    path:  /tags.{_format}
    defaults: { _controller: Entity\Tag:getAll, _format: json, entity: 'tags' }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml

api_post_tag:
    path:  /tags.{_format}
    defaults: { _controller: Entity\Tag:post, _format: json, entity: 'tags' }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_tag:
    path:  /tags/{id}.{_format}
    defaults: { _controller: Entity\Tag:patch, _format: json, entity: 'tags' }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_tag:
    path:  /tags/{id}.{_format}
    defaults: { _controller: Entity\Tag:put, _format: json, entity: 'tags' }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_tag:
    path:  /tags/{id}.{_format}
    defaults: { _controller: Entity\Tag:delete, _format: json, entity: 'tags' }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_typeahead_tags:
    path:  /typeahead/tags.{_format}
    defaults: { _controller: Entity\Tag:typeahead, _format: json }
    methods: [GET|OPTIONS]
    requirements:
        _format:  json|xml
