api_get_user_quickbooks:
    path: /users/{id}/quickbooks.{_format}
    defaults: { _controller: Entity\UserQuickbooks:get, _format: json, entity: "user_quickbooks" }
    methods: [GET|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_post_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: Entity\UserQuickbooks:post, _format: json, entity: "user_quickbooks" }
    methods: [POST|OPTIONS]
    requirements:
        _format:  json|xml

api_patch_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: Entity\UserQuickbooks:patch, _format: json, entity: "user_quickbooks" }
    methods: [PATCH|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_put_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: Entity\UserQuickbooks:put, _format: json, entity: "user_quickbooks" }
    methods: [PUT|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml

api_delete_user_quickbooks:
    path:  /users/{id}/quickbooks.{_format}
    defaults: { _controller: Entity\UserQuickbooks:delete, _format: json, entity: "user_quickbooks" }
    methods: [DELETE|OPTIONS]
    requirements:
        id: \d+
        _format:  json|xml