<?php

namespace Tavro\Bundle\CoreBundle\Repository;

/**
 * NodeReadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeReadRepository extends \Doctrine\ORM\EntityRepository
{
}
