<?php

namespace Tavro\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeReadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeReadRepository extends EntityRepository
{
}
