#!/usr/bin/env php

<?php

    printf("Execute `pre-commit` hook(s)\n", PHP_EOL);

    $projectName = basename(getcwd());

    printf("Running PHPUnit tests\n");
    exec('cd api && phpunit', $output, $returnCode);

    if ($returnCode !== 0) {
        $minimalTestSummary = array_pop($output);
        printf("Test suite for %s failed: ", $projectName);
        printf("( %s ) %s%2\$s", $minimalTestSummary, PHP_EOL);
        printf("ABORTING COMMIT!\n");
        exit(1);
    }

    printf("Done\n");

exit(0);
