---
- hosts: localhost
  vars:
    dbname: "{{dbname}}"
    dbpass: "{{dbpass}}"
    dbuser: "{{dbuser}}"
    dbhost: "{{dbhost}}"
    api_root: /var/www/tavro/api/
    core_fixture_path: src/Tavro/Bundle/CoreBundle/DataFixtures/ORM/Core/v1

  tasks:
    - name: drop database
      shell: mysql -u{{dbuser}} -p{{dbpass}} -e "DROP DATABASE IF EXISTS {{dbname}}"

    - name: recreate database
      shell: sudo php {{api_root}}bin/console doctrine:database:create

    - name: execute migrations
      shell: sudo php {{api_root}}bin/console doctrine:migrations:migrate --no-interaction

    - name: setup core data fixtures
      shell: sudo php {{api_root}}bin/console doctrine:fixtures:load --fixtures={{api_root}}{{core_fixture_path}} --append