---
- name: regenerate docs
  command: bash /var/www/{{appname}}/scripts/regenerate-docs.sh

- name: Copy AWS json API config..
  template: src=aws.json.j2 dest=/var/www/{{appname}}/api/aws.json

- name: Copy PHPUNIT config..
  template: src=phpunit.xml.j2 dest=/var/www/{{appname}}/api/phpunit.xml

- name: setup symfony binary alias
  command: ln -s /var/www/{{appname}}/api/bin/console /var/www/{{appname}}/api/symfony